
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame3")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("560x759")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 759,
    width = 560,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    280.0,
    379.0,
    image=image_image_1
)

canvas.create_text(
    39.0,
    69.0,
    anchor="nw",
    text="Receipe name",
    fill="#F7F7F7",
    font=("Inika", 36 * -1)
)

canvas.create_rectangle(
    0.0,
    0.0,
    560.0,
    54.0,
    fill="#702424",
    outline="")

canvas.create_text(
    73.0,
    5.0,
    anchor="nw",
    text="Add  Receipe",
    fill="#FFFFFF",
    font=("Inika Bold", 36 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    400.5,
    96.5,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=299.0,
    y=77.0,
    width=203.0,
    height=37.0
)

canvas.create_text(
    38.0,
    136.0,
    anchor="nw",
    text="Ingredients",
    fill="#FFFFFF",
    font=("Inika", 36 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    288.5,
    209.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=48.0,
    y=189.0,
    width=481.0,
    height=39.0
)

canvas.create_text(
    34.0,
    245.0,
    anchor="nw",
    text="Instructions",
    fill="#FFFFFF",
    font=("Inika", 36 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    286.5,
    392.0,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=44.0,
    y=303.0,
    width=485.0,
    height=176.0
)

canvas.create_text(
    34.0,
    489.0,
    anchor="nw",
    text="Receipe Video Link",
    fill="#FFFFFF",
    font=("Inika", 36 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=34.0,
    y=662.0,
    width=151.0,
    height=56.0
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    286.5,
    582.5,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=44.0,
    y=542.0,
    width=485.0,
    height=79.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=204.0,
    y=663.0,
    width=151.0,
    height=56.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=384.0,
    y=663.0,
    width=151.0,
    height=56.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    30.0,
    28.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
