
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/Users/arjun/FlavourFusion-GUI/build/assets/frame7")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1096x661")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 661,
    width = 1096,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    548.0,
    330.0,
    image=image_image_1
)

canvas.create_rectangle(
    0.0,
    0.0,
    1096.0,
    71.0,
    fill="#783000",
    outline="")

canvas.create_text(
    92.0,
    12.0,
    anchor="nw",
    text="Add Your Receipe",
    fill="#FFFFFF",
    font=("Inika Bold", 36 * -1)
)

canvas.create_text(
    39.0,
    93.0,
    anchor="nw",
    text="Receipe Name",
    fill="#FAFAFA",
    font=("Inika Bold", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    578.0,
    119.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=374.0,
    y=93.0,
    width=408.0,
    height=50.0
)

canvas.create_text(
    39.0,
    167.0,
    anchor="nw",
    text="Enter Ingredients",
    fill="#FFFFFF",
    font=("Inika Bold", 40 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    544.5,
    262.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=49.0,
    y=234.0,
    width=991.0,
    height=55.0
)

canvas.create_text(
    39.0,
    304.0,
    anchor="nw",
    text="Enter the Instructions",
    fill="#FFFFFF",
    font=("Inika Bold", 40 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    548.0,
    440.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#D9D9D9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=49.0,
    y=356.0,
    width=998.0,
    height=167.0
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=39.0,
    y=561.0,
    width=224.0,
    height=71.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=331.0,
    y=561.0,
    width=224.0,
    height=71.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    38.0,
    35.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
