
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import subprocess
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_file(pyfile):
    subprocess.run(["python3", pyfile])

window = Tk()

window.geometry("915x610")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 610,
    width = 915,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    457.0,
    305.0,
    image=image_image_1
)

canvas.create_text(
    493.0,
    320.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Inika", 36 * -1)
)

canvas.create_text(
    443.0,
    153.0,
    anchor="nw",
    text="Login",
    fill="#FFFFFF",
    font=("Inika Bold", 40 * -1)
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    749.5,
    336.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#B3AFAF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=664.0,
    y=320.0,
    width=171.0,
    height=30.0
)

canvas.create_text(
    474.0,
    386.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inika", 32 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    749.5,
    410.5,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#B4AFAF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=664.0,
    y=393.0,
    width=171.0,
    height=33.0
)

#Sign In
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file("Homepage.py"),
    relief="flat"
)
button_1.place(
    x=684.0,
    y=469.0,
    width=131.0,
    height=44.0
)
window.resizable(False, False)
window.mainloop()
