
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
import subprocess
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"./assets/frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def open_file(pyfile):
    subprocess.run(["python3", pyfile])

window = Tk()

window.geometry("578x658")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 658,
    width = 578,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    289.0,
    329.0,
    image=image_image_1
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    287.5,
    242.0,
    image=entry_image_1
)
entry_1 = Text(
    bd=0,
    bg="#CFB9B9",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=138.0,
    y=225.0,
    width=299.0,
    height=32.0
)

canvas.create_text(
    133.0,
    196.0,
    anchor="nw",
    text="Name",
    fill="#000000",
    font=("Inika", 16 * -1)
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    289.5,
    478.5,
    image=entry_image_2
)
entry_2 = Text(
    bd=0,
    bg="#CFB9B9",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=140.0,
    y=462.0,
    width=299.0,
    height=31.0
)

canvas.create_text(
    135.0,
    423.0,
    anchor="nw",
    text="Phone No",
    fill="#000000",
    font=("Inika", 16 * -1)
)

entry_image_3 = PhotoImage(
    file=relative_to_assets("entry_3.png"))
entry_bg_3 = canvas.create_image(
    289.5,
    397.5,
    image=entry_image_3
)
entry_3 = Text(
    bd=0,
    bg="#CFB9B9",
    fg="#000716",
    highlightthickness=0
)
entry_3.place(
    x=140.0,
    y=381.0,
    width=299.0,
    height=31.0
)

canvas.create_text(
    135.0,
    273.0,
    anchor="nw",
    text="Email",
    fill="#000000",
    font=("Inika", 16 * -1)
)

entry_image_4 = PhotoImage(
    file=relative_to_assets("entry_4.png"))
entry_bg_4 = canvas.create_image(
    289.5,
    318.0,
    image=entry_image_4
)
entry_4 = Text(
    bd=0,
    bg="#CFB9B9",
    fg="#000716",
    highlightthickness=0
)
entry_4.place(
    x=140.0,
    y=301.0,
    width=299.0,
    height=32.0
)

canvas.create_text(
    133.0,
    350.0,
    anchor="nw",
    text="Password",
    fill="#000000",
    font=("Inika", 16 * -1)
)

canvas.create_text(
    188.0,
    110.0,
    anchor="nw",
    text="Register Here",
    fill="#000000",
    font=("Inika Bold", 32 * -1)
)

#Register Button
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_file("Login.py"),
    relief="flat"
)
button_1.place(
    x=224.0,
    y=520.0,
    width=131.0,
    height=44.0
)
window.resizable(False, False)
window.mainloop()
